name: Publish
on:
  release:
    types: [published]
  workflow_dispatch:
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org

      - name: Added node cache
        uses: egordm/gha-yarn-node-cache@v1

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Linting affected projects
        run: yarn nx affected --target=lint --base=main

      - name: Testing affected projects
        run: yarn nx affected --target=test --base=main

      - name: Building affected projects
        run: yarn nx affected --target=build --base=main

      - name: Publish affected projects
        run: yarn nx affected --target=publish --base=main
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}}
