name: Publish
on:
  release:
    types: [published]
jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: [nestjs-test-utilities]

    steps:
      - name: Git Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: 'https://registry.npmjs.org'
          scope: '@jbiskur'

      - name: Added node cache
        uses: egordm/gha-yarn-node-cache@v1

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Linting projects
        run: yarn nx lint ${{ matrix.project }}

      - name: Testing projects
        run: yarn nx test ${{ matrix.project }}

      - name: Building projects
        run: yarn nx build ${{ matrix.project }}

      - name: Publish projects
        run: yarn publish --cwd ./dist/packages/${{ matrix.project }} --new-version ${{ github.event.release.tag_name }} --no-git-tag-version --access public --verbose
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
