name: Tests
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - run: git fetch --no-tags --prune --depth=5 origin main

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: "https://registry.npmjs.org"
          scope: "@jbiskur"

      - name: Added node cache
        uses: egordm/gha-yarn-node-cache@v1

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Linting affected projects
        run: yarn nx affected:lint --base=origin/main

      - name: Testing affected projects
        run: yarn nx affected:test --base=origin/main --codeCoverage
